// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using processDataShare.Data;

#nullable disable

namespace processDataShare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("processDataShare.Models.OpelArmrestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cycleTime")
                        .HasColumnType("int");

                    b.Property<int>("foldingSetPointMax")
                        .HasColumnType("int");

                    b.Property<int>("foldingTime")
                        .HasColumnType("int");

                    b.Property<int>("heatingSetPointMax")
                        .HasColumnType("int");

                    b.Property<int>("heatingTime")
                        .HasColumnType("int");

                    b.Property<int>("mouldNumber")
                        .HasColumnType("int");

                    b.Property<bool>("pyroIndicatorOnOff")
                        .HasColumnType("bit");

                    b.Property<int>("recipe")
                        .HasColumnType("int");

                    b.Property<DateTime>("shotDateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("tempLeftDown")
                        .HasColumnType("real");

                    b.Property<float>("tempLeftUp")
                        .HasColumnType("real");

                    b.Property<float>("tempRightDown")
                        .HasColumnType("real");

                    b.Property<float>("tempRightUp")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("OpelArmrestDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
